### ISSUE TITLE
yarss2 on asustor deluge 

### ISSUE THREAD

**Issue by Ragsie** [tremby/deluge-yarss-plugin#1]
hi

i simply cant get it to work.... i've downloaded 1.4.3 py2.7
my nas is running py2.7.10 and gcc 4.6.3

i can install it but i wont let me enable it

thanks in adv

**Comment by tremby** [comment]
This is abandoned, so I won't be providing support. I don't use it any
more. Try the upstream repository or, failing that, investigate
alternatives such as Flexget.

>
/close
